apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - prod-ingress.yaml

patches:
  - path: patch-deployment.yaml

configMapGenerator:
  - name: devops-config
    behavior: replace
    literals:
      - APP_PORT=9002

secretGenerator:
  - name: devops-secret
    behavior: replace
    literals:
      - SECRET_KEY=supersecurevalue
