apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      serviceAccountName: devops-api-sa
      securityContext:
        runAsUser: 65532
        runAsNonRoot: true
        fsGroup: 2000
      containers:
        - name: api
          image: <REPLACE_ME>
          ports:
            - containerPort: 9002
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: devops-config
                  key: APP_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-secret
                  key: SECRET_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: log-agent
          image: busybox
          command: ["sh", "-c", "tail -n+1 -F /var/log/app/app.log"]
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"

      volumes:
        - name: app-logs
          emptyDir: {}
