name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
      - feature/**
      - setup/**
      - "**"
  pull_request:
    branches:
      - main
      - feature/**
      - setup/**
      - "**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var-file=env/local.tfvars
        working-directory: ./terraform
